<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE storageClientFactory [

<!ELEMENT storageClientFactory (testStorage) >

<!ELEMENT testStorage (playlist*) >
<!ATTLIST testStorage tempFiles CDATA       #REQUIRED >

<!ELEMENT playlist (playlistElement*) >
<!ATTLIST playlist id           NMTOKEN     #REQUIRED >
<!ATTLIST playlist playlength   NMTOKEN     #REQUIRED >

<!ELEMENT playlistElement (audioClip) >
<!ATTLIST playlistElement id              NMTOKEN     #REQUIRED >
<!ATTLIST playlistElement relativeOffset  NMTOKEN     #REQUIRED >

<!ELEMENT audioClip EMPTY >
<!ATTLIST audioClip id              NMTOKEN     #REQUIRED >
<!ATTLIST audioClip playlength      NMTOKEN     #REQUIRED >
<!ATTLIST audioClip uri             CDATA       #REQUIRED >
]>
<storageClientFactory>
    <testStorage tempFiles="file:///tmp/tempPlaylist">
        <playlist id="1" playlength="01:30:00.000">
            <playlistElement id="101" relativeOffset="0" >
                <audioClip id="10001" playlength="01:00:00.000" 
                           uri="file:var/test1.mp3" />
            </playlistElement>
            <playlistElement id="102" relativeOffset="01:00:00.000" >
                <audioClip id="10002"  playlength="00:30:00.000" 
                           uri="file:var/test2.mp3" />
            </playlistElement>
        </playlist>
    </testStorage>
</storageClientFactory>
