<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE gLiveSupport [

<!ELEMENT gLiveSupport                (resourceBundle,
                                       supportedLanguages,
                                       gladeDirectory,
                                       widgetFactory,
                                       authenticationClientFactory,
                                       storageClientFactory,
                                       schedulerClientFactory,
                                       schedulerDaemonCommands,
                                       outputPlayer,
                                       cuePlayer,
                                       stationLogo,
                                       taskbarIcons,
                                       testAudioUrl,
                                       serialPort,
                                       rdsContainer,
                                       metadataTypeContainer,
                                       keyboardShortcutList) >

<!ELEMENT resourceBundle    EMPTY >
<!ATTLIST resourceBundle    path    CDATA   #REQUIRED >
<!ATTLIST resourceBundle    locale  CDATA   #REQUIRED >

<!ELEMENT supportedLanguages    (language+) >

<!ELEMENT language          EMPTY >
<!ATTLIST language          locale          CDATA   #REQUIRED >
<!ATTLIST language          name            CDATA   #REQUIRED >

<!ELEMENT gladeDirectory    EMPTY >
<!ATTLIST gladeDirectory    path            CDATA   #REQUIRED >

<!ELEMENT widgetFactory   EMPTY >
<!ATTLIST widgetFactory   path        CDATA   #REQUIRED >

<!ELEMENT authenticationClientFactory (testAuthentication|
                                       webAuthentication)>

<!ELEMENT testAuthentication (user) >

<!ELEMENT webAuthentication (location) >

<!ELEMENT location EMPTY >
<!ATTLIST location server   CDATA       #REQUIRED >
<!ATTLIST location port     NMTOKEN     #REQUIRED >
<!ATTLIST location path     CDATA       #REQUIRED >

<!ELEMENT user EMPTY >
<!ATTLIST user login        CDATA       #REQUIRED >
<!ATTLIST user password     CDATA       #REQUIRED >

<!ELEMENT storageClientFactory (testStorage|webStorage) >

<!ELEMENT testStorage (playlist*, audioClip*) >
<!ATTLIST testStorage tempFiles CDATA       #REQUIRED >

<!ELEMENT playlist (playlistElement*) >
<!ATTLIST playlist id           NMTOKEN     #REQUIRED >
<!ATTLIST playlist playlength   NMTOKEN     #REQUIRED >

<!ELEMENT playlistElement ((audioClip|playlist), fadeInfo?) >
<!ATTLIST playlistElement id              NMTOKEN     #REQUIRED >
<!ATTLIST playlistElement relativeOffset  NMTOKEN     #REQUIRED >

<!ELEMENT audioClip EMPTY >
<!ATTLIST audioClip id              NMTOKEN     #REQUIRED >
<!ATTLIST audioClip playlength      NMTOKEN     #REQUIRED >
<!ATTLIST audioClip title           CDATA       #REQUIRED >
<!ATTLIST audioClip uri             CDATA       #REQUIRED >

<!ELEMENT fadeInfo EMPTY >
<!ATTLIST fadeInfo id              NMTOKEN     #REQUIRED >
<!ATTLIST fadeInfo fadeIn          NMTOKEN     #REQUIRED >
<!ATTLIST fadeInfo fadeOut         NMTOKEN     #REQUIRED >

<!ELEMENT webStorage (location) >
<!ATTLIST webStorage tempFiles CDATA       #REQUIRED >

<!ELEMENT schedulerClientFactory        (schedulerDaemonXmlRpcClient) >

<!ELEMENT schedulerDaemonXmlRpcClient   EMPTY >
<!ATTLIST schedulerDaemonXmlRpcClient xmlRpcHost    CDATA       #REQUIRED >
<!ATTLIST schedulerDaemonXmlRpcClient xmlRpcPort    NMTOKEN     #REQUIRED >
<!ATTLIST schedulerDaemonXmlRpcClient xmlRpcUri     CDATA       #REQUIRED >

<!ELEMENT schedulerDaemonCommands       EMPTY >
<!ATTLIST schedulerDaemonCommands   start           CDATA       #REQUIRED >
<!ATTLIST schedulerDaemonCommands   stop            CDATA       #REQUIRED >

<!ELEMENT outputPlayer  (audioPlayer) >
<!ELEMENT cuePlayer     (audioPlayer) >

<!ELEMENT audioPlayer   (gstreamerPlayer) >

<!ELEMENT gstreamerPlayer   EMPTY >
<!ATTLIST gstreamerPlayer   audioDevice  CDATA   #IMPLIED  >

<!ELEMENT stationLogo    EMPTY >
<!ATTLIST stationLogo    path    CDATA   #REQUIRED >

<!ELEMENT taskbarIcons   (icon+)                   >
<!ELEMENT icon           EMPTY                     >
<!ATTLIST icon           path    CDATA   #REQUIRED >

<!ELEMENT testAudioUrl   EMPTY >
<!ATTLIST testAudioUrl   path    CDATA   #REQUIRED >

<!ELEMENT serialPort     EMPTY                     >
<!ATTLIST serialPort     path    CDATA   #REQUIRED >

<!ELEMENT rdsContainer   (rdsItem*) >
<!ELEMENT rdsItem        EMPTY      >
<!ATTLIST rdsItem        key        CDATA   #REQUIRED >
<!ATTLIST rdsItem        value      CDATA   #REQUIRED >
<!ATTLIST rdsItem        enabled    CDATA   #REQUIRED >

<!ELEMENT metadataTypeContainer           (metadataType+)       >

<!ELEMENT metadataType                    (constraint?)         >
<!ATTLIST metadataType  dcName            NMTOKEN     #REQUIRED >
<!ATTLIST metadataType  id3Tag            CDATA       #IMPLIED  >
<!ATTLIST metadataType  localizationKey   CDATA       #REQUIRED >
<!ATTLIST metadataType  tab               NMTOKEN     #IMPLIED  >

<!ELEMENT constraint                      (value*)              >
<!ATTLIST constraint    type              NMTOKEN     #REQUIRED >

<!ELEMENT value                           (#PCDATA)             >

<!ELEMENT keyboardShortcutList          (keyboardShortcutContainer*) >
<!ELEMENT keyboardShortcutContainer     (keyboardShortcut+)          >
<!ATTLIST keyboardShortcutContainer windowName  CDATA   #REQUIRED    >

<!ELEMENT keyboardShortcut  EMPTY >
<!ATTLIST keyboardShortcut  action      CDATA   #REQUIRED >
<!ATTLIST keyboardShortcut  key         CDATA   #REQUIRED >

]>

<gLiveSupport>
    <resourceBundle path   = "./tmp/studio-localization"
                    locale = "en"
    />

    <supportedLanguages>
        <language locale="en"               name="English"/>
        <language locale="es"               name="Español"/>
        <language locale="fr"               name="Français"/>
        <language locale="hu"               name="Magyar"/>
        <language locale="nl"               name="Nederlands"/>
        <language locale="pl"               name="Polski"/>
        <language locale="sr_CS"            name="Srpski"/>
        <language locale="sr_CS_CYRILLIC"   name="Српски"/>
        <language locale="sv"               name="Svenska"/>
    </supportedLanguages>

    <gladeDirectory     path = "./var/glade/" />

    <widgetFactory    path = "var/widgets/" />

    <authenticationClientFactory>
        <webAuthentication>
            <location server="localhost" port="80"
                      path="/campcasterStorageServer/xmlrpc/xrLocStor.php" />
        </webAuthentication>
    </authenticationClientFactory>

    <storageClientFactory>
        <webStorage tempFiles="file:///tmp/campcasterStudioStorageClient" >
            <location server="localhost" port="80" 
                      path="/campcasterStorageServer/xmlrpc/xrLocStor.php" />
        </webStorage>
    </storageClientFactory>

    <schedulerClientFactory>
        <schedulerDaemonXmlRpcClient    xmlRpcHost = "localhost"
                                        xmlRpcPort = "3344"
                                        xmlRpcUri  = "/RC2"
        />
    </schedulerClientFactory>

    <schedulerDaemonCommands
            start = "../scheduler/bin/campcaster-scheduler_devenv.sh start"
            stop  = "../scheduler/bin/campcaster-scheduler_devenv.sh stop" />

    <outputPlayer>
        <audioPlayer>
            <gstreamerPlayer audioDevice = "default" />
        </audioPlayer>
    </outputPlayer>

    <cuePlayer>
        <audioPlayer>
            <gstreamerPlayer audioDevice = "default" />
        </audioPlayer>
    </cuePlayer>

    <stationLogo    path = "var/stationLogo.png" />

    <taskbarIcons>
        <icon       path = "var/icon16.png" />
        <icon       path = "var/icon22.png" />
        <icon       path = "var/icon32.png" />
        <icon       path = "var/icon48.png" />
    </taskbarIcons>

    <testAudioUrl   path = "file://var/testAudio.ogg" />

    <serialPort     path = "/dev/ttyS0" />

    <rdsContainer>
        <rdsItem key="PS" value="" enabled="0"/>
        <rdsItem key="PI" value="" enabled="0"/>
        <rdsItem key="RT" value="" enabled="0"/>
    </rdsContainer>

    <metadataTypeContainer>
        <metadataType   dcName          = "dc:title"
                        id3Tag          = "TIT2"
                        localizationKey = "title"
                        tab             = "main"
        />
        <metadataType   dcName          = "dc:creator"
                        id3Tag          = "TPE1"
                        localizationKey = "creator"
                        tab             = "main"
        />
        <metadataType   dcName          = "dc:source"
                        id3Tag          = "TALB"
                        localizationKey = "album"
                        tab             = "music"
        />
        <metadataType   dcName          = "ls:year"
                        id3Tag          = "TYER"
                        localizationKey = "year"
                        tab             = "music" >
            <constraint type            = "numericRange" >
                <value>0</value>
                <value>3000</value>
            </constraint>
        </metadataType>
        <metadataType   dcName          = "dc:type"
                        id3Tag          = "TCON"
                        localizationKey = "genre"
                        tab             = "main"
        />
        <metadataType   dcName          = "dc:description"
                        id3Tag          = "COMM"
                        localizationKey = "description"
                        tab             = "main"
        />
        <metadataType   dcName          = "dc:format"
                        localizationKey = "format" >
            <constraint type            = "enumeration" >
                <value>mp3</value>
                <value>mpeg</value>
                <value>ogg</value>
            </constraint>
        </metadataType>
        <metadataType   dcName          = "ls:bpm"
                        id3Tag          = "TBPM"
                        localizationKey = "bpm"
                        tab             = "music" >
            <constraint type            = "numeric" />
        </metadataType>
        <metadataType   dcName          = "ls:rating"
                        id3Tag          = "POPM"
                        localizationKey = "rating"
                        tab             = "music"
        />
        <metadataType   dcName          = "dcterms:extent"
                        localizationKey = "length"
        />
        <metadataType   dcName          = "ls:encoded_by"
                        id3Tag          = "TENC"
                        localizationKey = "encoded_by"
                        tab             = "music"
        />
        <metadataType   dcName          = "ls:track_num"
                        id3Tag          = "TRCK"
                        localizationKey = "track_number"
                        tab             = "music" >
        </metadataType>
        <metadataType   dcName          = "ls:disc_num"
                        id3Tag          = "TPOS"
                        localizationKey = "disc_number"
                        tab             = "music" >
            <constraint type            = "numeric" />
        </metadataType>
        <metadataType   dcName          = "ls:mood"
                        id3Tag          = "TMOO"
                        localizationKey = "mood"
                        tab             = "music"
        />
        <metadataType   dcName          = "dc:publisher"
                        id3Tag          = "TPUB"
                        localizationKey = "publishing_label"
                        tab             = "music"
        />
        <metadataType   dcName          = "ls:composer"
                        id3Tag          = "TCOM"
                        localizationKey = "composer"
                        tab             = "music"
        />
        <metadataType   dcName          = "ls:bitrate"
                        localizationKey = "bitrate"
                        tab             = "music" >
            <constraint type            = "numeric" />
        </metadataType>
        <metadataType   dcName          = "ls:channels"
                        localizationKey = "channels"
                        tab             = "music"
        />
        <metadataType   dcName          = "ls:samplerate"
                        localizationKey = "sample_rate"
                        tab             = "music" >
            <constraint type            = "numeric" />
        </metadataType>
        <metadataType   dcName          = "ls:encoder"
                        id3Tag          = "TSSE"
                        localizationKey = "encoding_software"
                        tab             = "music"
        />
        <metadataType   dcName          = "ls:crc"
                        localizationKey = "checksum"
        />
        <metadataType   dcName          = "ls:lyrics"
                        localizationKey = "lyrics"
                        tab             = "music"
        />
        <metadataType   dcName          = "ls:orchestra"
                        id3Tag          = "TPE2"
                        localizationKey = "orchestra_or_band"
                        tab             = "music"
        />
        <metadataType   dcName          = "ls:conductor"
                        id3Tag          = "TPE3"
                        localizationKey = "conductor"
                        tab             = "music"
        />
        <metadataType   dcName          = "ls:lyricist"
                        id3Tag          = "TEXT"
                        localizationKey = "lyricist"
                        tab             = "music"
        />
        <metadataType   dcName          = "ls:originallyricist"
                        id3Tag          = "TOLY"
                        localizationKey = "original_lyricist"
                        tab             = "music"
        />
        <metadataType   dcName          = "ls:radiostationname"
                        id3Tag          = "TRSN"
                        localizationKey = "radio_station_name"
        />
        <metadataType   dcName          = "ls:audiofileinfourl"
                        id3Tag          = "WOAF"
                        localizationKey = "audio_file_info_url"
        />
        <metadataType   dcName          = "ls:artisturl"
                        id3Tag          = "WOAR"
                        localizationKey = "artist_url"
        />
        <metadataType   dcName          = "ls:audiosourceurl"
                        id3Tag          = "WOAS"
                        localizationKey = "audio_source_url"
        />
        <metadataType   dcName          = "ls:radiostationurl"
                        id3Tag          = "WORS"
                        localizationKey = "radio_station_url"
        />
        <metadataType   dcName          = "ls:buycdurl"
                        id3Tag          = "WPAY"
                        localizationKey = "buy_cd_url"
        />
        <metadataType   dcName          = "ls:isrcnumber"
                        id3Tag          = "TSRC"
                        localizationKey = "isrc_number"
        />
        <metadataType   dcName          = "ls:catalognumber"
                        localizationKey = "catalog_number"
        />
        <metadataType   dcName          = "ls:originalartist"
                        id3Tag          = "TOPE"
                        localizationKey = "original_artist"
                        tab             = "music"
        />
        <metadataType   dcName          = "dc:rights"
                        id3Tag          = "TCOP"
                        localizationKey = "copyright"
                        tab             = "music"
        />
        <metadataType   dcName          = "dcterms:temporal"
                        localizationKey = "report_date_time"
                        tab             = "voice"
        />
        <metadataType   dcName          = "dcterms:spatial"
                        localizationKey = "report_location"
                        tab             = "voice"
        />
        <metadataType   dcName          = "dcterms:entity"
                        localizationKey = "report_organizations"
                        tab             = "voice"
        />
        <metadataType   dcName          = "dc:subject"
                        localizationKey = "subject"
                        tab             = "voice"
        />
    </metadataTypeContainer>
    
    <keyboardShortcutList>
        <keyboardShortcutContainer
                    windowName = "masterPanelWindow">
            <keyboardShortcut   action  = "playAudio"   key = "X" />
            <keyboardShortcut   action  = "pauseAudio"  key = "V" />
            <keyboardShortcut   action  = "stopAudio"   key = "C" />
            <keyboardShortcut   action  = "nextTrack"   key = "B" />
        </keyboardShortcutContainer>

        <keyboardShortcutContainer
                    windowName = "liveModeWindow">
            <keyboardShortcut   action  = "moveItemUp"
                                key     = "&lt;Alt&gt;Up"   />
            <keyboardShortcut   action  = "moveItemDown"
                                key     = "&lt;Alt&gt;Down" />
            <keyboardShortcut   action  = "removeItem"    key = "Delete" />
            <keyboardShortcut   action  = "playAudio"     key = "X"      />
        </keyboardShortcutContainer>

        <keyboardShortcutContainer
                    windowName = "scratchpadWindow">
            <keyboardShortcut   action  = "moveItemUp"
                                key     = "&lt;Alt&gt;Up"   />
            <keyboardShortcut   action  = "moveItemDown"
                                key     = "&lt;Alt&gt;Down" />
            <keyboardShortcut   action  = "removeItem"    key = "Delete" />
        </keyboardShortcutContainer>

        <keyboardShortcutContainer
                    windowName ="playlistWindow">
            <keyboardShortcut   action  = "moveItemUp"
                                key     = "&lt;Alt&gt;Up"   />
            <keyboardShortcut   action  = "moveItemDown"
                                key     = "&lt;Alt&gt;Down" />
            <keyboardShortcut   action  = "removeItem"    key = "Delete" />
        </keyboardShortcutContainer>
    </keyboardShortcutList>

</gLiveSupport>

