<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE gLiveSupport [

<!ELEMENT gLiveSupport                (resourceBundle,
                                       supportedLanguages,
                                       authenticationClientFactory,
                                       storageClientFactory,
                                       schedulerClientFactory) >

<!ELEMENT resourceBundle    EMPTY >
<!ATTLIST resourceBundle    path    CDATA   #REQUIRED >
<!ATTLIST resourceBundle    locale  CDATA   #REQUIRED >

<!ELEMENT supportedLanguages    (language+) >

<!ELEMENT language          EMPTY >
<!ATTLIST language          locale          CDATA #REQUIRED >
<!ATTLIST language          name            CDATA #REQUIRED >

<!ELEMENT authenticationClientFactory (testAuthentication|
                                       webAuthentication)>

<!ELEMENT testAuthentication (user) >

<!ELEMENT user EMPTY >
<!ATTLIST user login        CDATA       #REQUIRED >
<!ATTLIST user password     CDATA       #REQUIRED >

<!ELEMENT storageClientFactory (testStorage|webStorage) >

<!ELEMENT testStorage (playlist*, audioClip*) >
<!ATTLIST testStorage tempFiles CDATA       #REQUIRED >

<!ELEMENT playlist (playlistElement*) >
<!ATTLIST playlist id           NMTOKEN     #REQUIRED >
<!ATTLIST playlist playlength   NMTOKEN     #REQUIRED >

<!ELEMENT playlistElement ((audioClip|playlist), fadeInfo?) >
<!ATTLIST playlistElement id              NMTOKEN     #REQUIRED >
<!ATTLIST playlistElement relativeOffset  NMTOKEN     #REQUIRED >

<!ELEMENT audioClip EMPTY >
<!ATTLIST audioClip id              NMTOKEN     #REQUIRED >
<!ATTLIST audioClip playlength      NMTOKEN     #REQUIRED >
<!ATTLIST audioClip uri             CDATA       #REQUIRED >

<!ELEMENT fadeInfo EMPTY >
<!ATTLIST fadeInfo id              NMTOKEN     #REQUIRED >
<!ATTLIST fadeInfo fadeIn          NMTOKEN     #REQUIRED >
<!ATTLIST fadeInfo fadeOut         NMTOKEN     #REQUIRED >

<!ELEMENT webStorage (location) >
<!ATTLIST webStorage tempFiles CDATA       #REQUIRED >

<!ELEMENT location EMPTY >
<!ATTLIST location server   CDATA       #REQUIRED >
<!ATTLIST location port     NMTOKEN     #REQUIRED >
<!ATTLIST location path     CDATA       #REQUIRED >

<!ELEMENT schedulerClientFactory        (schedulerDaemonXmlRpcClient) >

<!ELEMENT schedulerDaemonXmlRpcClient   EMPTY >
<!ATTLIST schedulerDaemonXmlRpcClient xmlRpcHost    CDATA       #REQUIRED >
<!ATTLIST schedulerDaemonXmlRpcClient xmlRpcPort    NMTOKEN     #REQUIRED >
<!ATTLIST schedulerDaemonXmlRpcClient xmlRpcUri     CDATA       #REQUIRED >

]>
<gLiveSupport>
    <resourceBundle path   = "./tmp/gLiveSupport"
                    locale = "en"
    />

    <supportedLanguages>
        <language locale="en" name="English"/>
        <language locale="hu" name="Magyar"/>
    </supportedLanguages>

    <authenticationClientFactory>
        <testAuthentication>
            <user login="root" password="q" />
        </testAuthentication>
    </authenticationClientFactory>

    <storageClientFactory>
        <testStorage tempFiles="file:///tmp/tempPlaylist">
            <playlist id="1" playlength="00:00:34.000" >
                <playlistElement id="101"    relativeOffset="0" >
                    <audioClip   id="10001"  playlength="00:00:11.000" 
                                 uri="file:var/test1.mp3" />
                </playlistElement>
                <playlistElement id="102"    relativeOffset="00:00:11.000000" >
                    <audioClip   id="10002"  playlength="00:00:12.000000" 
                                 uri="file:var/test2.mp3" /> 
                    <fadeInfo    id="9901"   fadeIn="00:00:02.000000" 
                                             fadeOut="00:00:01.500000" />
                </playlistElement>
                <playlistElement id="103"    relativeOffset="00:00:23.000000" >
                    <playlist    id="2"      playlength="00:00:11.000000" > 
                        <playlistElement id="111"    relativeOffset="0" >
                            <audioClip   id="10003"  playlength="00:00:11.000" 
                                         uri="file:var/test3.mp3" />
                        </playlistElement>
                    </playlist>
                </playlistElement>
            </playlist>
            <playlist    id="2"      playlength="00:00:11.000000" > 
                <playlistElement id="111"    relativeOffset="0" >
                    <audioClip   id="10003"  playlength="00:00:11.000" 
                                    uri="file:var/test3.mp3" />
                </playlistElement>
            </playlist>
            <audioClip id="10001" playlength="01:00:00.000" 
                       uri="file:var/test1.mp3" />
            <audioClip id="10002" playlength="00:30:00.000" 
                       uri="file:var/test2.mp3" /> 
        </testStorage>
    </storageClientFactory>

    <schedulerClientFactory>
        <schedulerDaemonXmlRpcClient    xmlRpcHost = "localhost"
                                        xmlRpcPort = "3344"
                                        xmlRpcUri  = "/RC2"
        />
    </schedulerClientFactory>

</gLiveSupport>

