<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE playlist [

<!ELEMENT playlist (playlistElement*) >
<!ATTLIST playlist id           NMTOKEN     #REQUIRED >
<!ATTLIST playlist playlength   NMTOKEN     #REQUIRED >

<!ELEMENT playlistElement ((audioClip|playlist), fadeInfo?) >
<!ATTLIST playlistElement id              NMTOKEN     #REQUIRED >
<!ATTLIST playlistElement relativeOffset  NMTOKEN     #REQUIRED >

<!ELEMENT audioClip EMPTY >
<!ATTLIST audioClip id              NMTOKEN     #REQUIRED >
<!ATTLIST audioClip playlength      NMTOKEN     #REQUIRED >
<!ATTLIST audioClip title            CDATA       #REQUIRED >
<!ATTLIST audioClip uri             CDATA       #IMPLIED  >

<!ELEMENT fadeInfo EMPTY >
<!ATTLIST fadeInfo id              NMTOKEN     #REQUIRED >
<!ATTLIST fadeInfo fadeIn          NMTOKEN     #REQUIRED >
<!ATTLIST fadeInfo fadeOut         NMTOKEN     #REQUIRED >
]>

<playlist id="0000000000000001" 
          playlength="00:00:34.000" >
    <playlistElement id="0000000000000101" 
                     relativeOffset="0" >
        <audioClip   id="0000000000010001" 
                     playlength="00:00:11.000" 
                     title = "one"
                     uri="file:var/test1.mp3" />
    </playlistElement>
    <playlistElement id="0000000000000102"    
                     relativeOffset="00:00:11.000000" >
        <audioClip   id="0000000000010002"  
                     playlength="00:00:12.000000" 
                     title = "two"
                     uri="file:var/test2.mp3" /> 
        <fadeInfo    id="0000000000009901"   
                     fadeIn="00:00:02.000000" 
                     fadeOut="00:00:01.500000" />
    </playlistElement>
    <playlistElement id="0000000000000103" 
                     relativeOffset="00:00:23.000000" >
        <playlist    id="0000000000000002" 
                     playlength="00:00:11.000000" > 
            <playlistElement id="0000000000000111" 
                             relativeOffset="0" >
                <audioClip   id="0000000000010003" 
                             playlength="00:00:11.000" 
                             title = "three"
                             uri="file:var/test3.mp3" />
            </playlistElement>
        </playlist>
    </playlistElement>
</playlist>
